# Final Ensembl115 BP analysis, using the original validated native enricher path.
args <- commandArgs(TRUE)
if (length(args)!=1) stop("Usage: Rscript enrich_final.R specification.json")
script <- sub("^--file=", "", grep("^--file=",commandArgs(),value=TRUE)[1])
source(file.path(dirname(normalizePath(script)), "common.R"))
suppressPackageStartupMessages(library(clusterProfiler))
spec <- jsonlite::read_json(args[1], simplifyVector=TRUE)
out <- spec$output
if (dir.exists(out)) stop("Use a new output directory")
dir.create(out, recursive=TRUE)
u <- read_tab(spec$gene_universe)
need(all(c("gene_id","selected") %in% names(u)), "Universe requires gene_id and selected")
need(!anyDuplicated(u$gene_id), "Duplicate gene in one tissue/mode job")
need(all(u$selected %in% c(0,1)), "selected must be 0 or 1")
en <- read_tab(spec$go_annotation)
need(all(c("go_id","gene_id","go_name") %in% names(en)), "Annotation requires go_id, gene_id, go_name")
t2g <- unique(data.frame(term=en$go_id,gene=en$gene_id))
t2n <- unique(data.frame(term=en$go_id,name=en$go_name))
background <- sorted_unique(u$gene_id);candidate <- sorted_unique(u$gene_id[u$selected==1])
fit <- enricher(gene=candidate,universe=background,TERM2GENE=t2g,TERM2NAME=t2n,
    pAdjustMethod="BH",pvalueCutoff=1,qvalueCutoff=1,minGSSize=10,maxGSSize=500)
validation <- validate_result(fit,t2g,background,candidate)
result <- if (is.null(fit)) empty_result() else fit@result
result$BH05 <- as.integer(!is.na(result$p.adjust) & result$p.adjust<=.05)
write_tab(result,file.path(out,"GO_BP_all_tested.tsv.gz"))
write_tab(result[result$BH05==1, ],file.path(out,"GO_BP_significant.tsv"))
write_tab(u,file.path(out,"gene_universe.tsv.gz"))
write_json(validation,file.path(out,"numerical_validation.json"))
saveRDS(fit,file.path(out,"enrichment_result.rds"))
capture.output(sessionInfo(),file=file.path(out,"sessionInfo.txt"))
